[context.production]
command = "echo $DEPLOY_PRIME_URL"
command = "npm run build && echo \"NEXTAUTH_URL=$URL\" > .env"

[context.deploy-preview]
command = "npm run build && echo \"NEXTAUTH_URL=$DEPLOY_PRIME_URL\" > .env"